FROM mcr.microsoft.com/dotnet/aspnet:6.0
RUN apt-get update && apt-get -y install procps openssh-server sudo
# disable sudo ask for password
RUN echo "ubuntu ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1001 -p debugpass ubuntu
USER ubuntu
WORKDIR /home/ubuntu