name: Build application base image

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - Images/Dockerfile.appbase


jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true
      - name: Build&Push
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Images/Dockerfile.appbase
          tags: ghcr.io/avabin/aspnet:latest
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          